# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Brendan/SkyDrive/maya/scripts/bkTools/surfRig/surfRigUi.ui'
#
# Created: Sat Jan 06 21:26:32 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from bkTools.Qt import QtCompat, QtCore, QtGui, QtWidgets

class Ui_SurfRigWindow(object):
    def setupUi(self, SurfRigWindow):
        SurfRigWindow.setObjectName("SurfRigWindow")
        SurfRigWindow.resize(434, 820)
        self.centralwidget = QtWidgets.QWidget(SurfRigWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.step1Layout = QtWidgets.QVBoxLayout()
        self.step1Layout.setContentsMargins(-1, 4, -1, 4)
        self.step1Layout.setObjectName("step1Layout")
        self.step1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.step1.setFont(font)
        self.step1.setObjectName("step1")
        self.step1Layout.addWidget(self.step1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.symLabel = QtWidgets.QLabel(self.centralwidget)
        self.symLabel.setObjectName("symLabel")
        self.horizontalLayout_4.addWidget(self.symLabel)
        self.symAxis = QtWidgets.QComboBox(self.centralwidget)
        self.symAxis.setObjectName("symAxis")
        self.symAxis.addItem("")
        self.symAxis.addItem("")
        self.symAxis.addItem("")
        self.symAxis.addItem("")
        self.horizontalLayout_4.addWidget(self.symAxis)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_4.addWidget(self.nameLabel)
        self.nameButton = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton.setObjectName("nameButton")
        self.horizontalLayout_4.addWidget(self.nameButton)
        self.step1Layout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.step1Layout)
        self.step2Layout = QtWidgets.QVBoxLayout()
        self.step2Layout.setContentsMargins(-1, 4, -1, 4)
        self.step2Layout.setObjectName("step2Layout")
        self.step2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.step2.setFont(font)
        self.step2.setTextFormat(QtCore.Qt.AutoText)
        self.step2.setScaledContents(False)
        self.step2.setObjectName("step2")
        self.step2Layout.addWidget(self.step2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.surfNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.surfNameLabel.setObjectName("surfNameLabel")
        self.horizontalLayout.addWidget(self.surfNameLabel)
        self.surfNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.surfNameEdit.setObjectName("surfNameEdit")
        self.horizontalLayout.addWidget(self.surfNameEdit)
        self.step2Layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.newSurfButton = QtWidgets.QPushButton(self.centralwidget)
        self.newSurfButton.setObjectName("newSurfButton")
        self.horizontalLayout_16.addWidget(self.newSurfButton)
        self.simpleSurfButton = QtWidgets.QPushButton(self.centralwidget)
        self.simpleSurfButton.setObjectName("simpleSurfButton")
        self.horizontalLayout_16.addWidget(self.simpleSurfButton)
        self.initSurfButton = QtWidgets.QPushButton(self.centralwidget)
        self.initSurfButton.setObjectName("initSurfButton")
        self.horizontalLayout_16.addWidget(self.initSurfButton)
        self.step2Layout.addLayout(self.horizontalLayout_16)
        self.verticalLayout.addLayout(self.step2Layout)
        self.step3Layout = QtWidgets.QHBoxLayout()
        self.step3Layout.setContentsMargins(-1, 4, -1, 4)
        self.step3Layout.setObjectName("step3Layout")
        self.step3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.step3.setFont(font)
        self.step3.setObjectName("step3")
        self.step3Layout.addWidget(self.step3)
        self.selectCVsButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectCVsButton.setObjectName("selectCVsButton")
        self.step3Layout.addWidget(self.selectCVsButton)
        self.toggleJntsButton = QtWidgets.QPushButton(self.centralwidget)
        self.toggleJntsButton.setObjectName("toggleJntsButton")
        self.step3Layout.addWidget(self.toggleJntsButton)
        self.toggleSurfsButton = QtWidgets.QPushButton(self.centralwidget)
        self.toggleSurfsButton.setObjectName("toggleSurfsButton")
        self.step3Layout.addWidget(self.toggleSurfsButton)
        self.verticalLayout.addLayout(self.step3Layout)
        self.step4Layout = QtWidgets.QVBoxLayout()
        self.step4Layout.setContentsMargins(-1, 4, -1, 4)
        self.step4Layout.setObjectName("step4Layout")
        self.step4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.step4.setFont(font)
        self.step4.setObjectName("step4")
        self.step4Layout.addWidget(self.step4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.jntNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.jntNameLabel.setObjectName("jntNameLabel")
        self.horizontalLayout_5.addWidget(self.jntNameLabel)
        self.jntNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.jntNameEdit.setObjectName("jntNameEdit")
        self.horizontalLayout_5.addWidget(self.jntNameEdit)
        self.newJntButton = QtWidgets.QPushButton(self.centralwidget)
        self.newJntButton.setObjectName("newJntButton")
        self.horizontalLayout_5.addWidget(self.newJntButton)
        self.step4Layout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.step4Layout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.step4Layout)
        self.step5Layout = QtWidgets.QVBoxLayout()
        self.step5Layout.setContentsMargins(-1, 4, -1, 4)
        self.step5Layout.setObjectName("step5Layout")
        self.step5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.step5.setFont(font)
        self.step5.setObjectName("step5")
        self.step5Layout.addWidget(self.step5)
        self.mirrorGrp = QtWidgets.QGroupBox(self.centralwidget)
        self.mirrorGrp.setCheckable(True)
        self.mirrorGrp.setChecked(True)
        self.mirrorGrp.setObjectName("mirrorGrp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mirrorGrp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mirrorBoth = QtWidgets.QRadioButton(self.mirrorGrp)
        self.mirrorBoth.setChecked(True)
        self.mirrorBoth.setObjectName("mirrorBoth")
        self.horizontalLayout_6.addWidget(self.mirrorBoth)
        self.mirrorJnts = QtWidgets.QRadioButton(self.mirrorGrp)
        self.mirrorJnts.setObjectName("mirrorJnts")
        self.horizontalLayout_6.addWidget(self.mirrorJnts)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.searchLabel = QtWidgets.QLabel(self.mirrorGrp)
        self.searchLabel.setObjectName("searchLabel")
        self.horizontalLayout_8.addWidget(self.searchLabel)
        self.searchEdit = QtWidgets.QLineEdit(self.mirrorGrp)
        self.searchEdit.setText("")
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout_8.addWidget(self.searchEdit)
        self.replaceLabel = QtWidgets.QLabel(self.mirrorGrp)
        self.replaceLabel.setObjectName("replaceLabel")
        self.horizontalLayout_8.addWidget(self.replaceLabel)
        self.replaceEdit = QtWidgets.QLineEdit(self.mirrorGrp)
        self.replaceEdit.setObjectName("replaceEdit")
        self.horizontalLayout_8.addWidget(self.replaceEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.step5Layout.addWidget(self.mirrorGrp)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rigButton = QtWidgets.QPushButton(self.centralwidget)
        self.rigButton.setObjectName("rigButton")
        self.horizontalLayout_3.addWidget(self.rigButton)
        self.rigAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.rigAllButton.setObjectName("rigAllButton")
        self.horizontalLayout_3.addWidget(self.rigAllButton)
        self.step5Layout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.sizeLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.sizeLabel.setObjectName("sizeLabel")
        self.horizontalLayout_10.addWidget(self.sizeLabel)
        self.sizeEdit = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sizeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sizeEdit.setDecimals(2)
        self.sizeEdit.setMinimum(0.01)
        self.sizeEdit.setMaximum(99.9)
        self.sizeEdit.setProperty("value", 0.5)
        self.sizeEdit.setObjectName("sizeEdit")
        self.horizontalLayout_10.addWidget(self.sizeEdit)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.sizeSlider = QtWidgets.QSlider(self.centralwidget)
        self.sizeSlider.setMinimum(1)
        self.sizeSlider.setMaximum(200)
        self.sizeSlider.setProperty("value", 50)
        self.sizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sizeSlider.setInvertedAppearance(False)
        self.sizeSlider.setInvertedControls(False)
        self.sizeSlider.setObjectName("sizeSlider")
        self.horizontalLayout_11.addWidget(self.sizeSlider)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 2)
        self.step5Layout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.distanceLabel = QtWidgets.QLabel(self.centralwidget)
        self.distanceLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.distanceLabel.setObjectName("distanceLabel")
        self.horizontalLayout_12.addWidget(self.distanceLabel)
        self.distanceEdit = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.distanceEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.distanceEdit.setDecimals(1)
        self.distanceEdit.setMinimum(0.0)
        self.distanceEdit.setMaximum(99.9)
        self.distanceEdit.setProperty("value", 0.5)
        self.distanceEdit.setObjectName("distanceEdit")
        self.horizontalLayout_12.addWidget(self.distanceEdit)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_12)
        self.distanceSlider = QtWidgets.QSlider(self.centralwidget)
        self.distanceSlider.setMaximum(50)
        self.distanceSlider.setProperty("value", 5)
        self.distanceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.distanceSlider.setObjectName("distanceSlider")
        self.horizontalLayout_9.addWidget(self.distanceSlider)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 2)
        self.step5Layout.addLayout(self.horizontalLayout_9)
        self.parGrp = QtWidgets.QGroupBox(self.centralwidget)
        self.parGrp.setObjectName("parGrp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.parGrp)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.newParButton = QtWidgets.QPushButton(self.parGrp)
        self.newParButton.setObjectName("newParButton")
        self.horizontalLayout_13.addWidget(self.newParButton)
        self.parExistingButton = QtWidgets.QPushButton(self.parGrp)
        self.parExistingButton.setObjectName("parExistingButton")
        self.horizontalLayout_13.addWidget(self.parExistingButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.mirParButton = QtWidgets.QPushButton(self.parGrp)
        self.mirParButton.setObjectName("mirParButton")
        self.horizontalLayout_14.addWidget(self.mirParButton)
        self.unparentButton = QtWidgets.QPushButton(self.parGrp)
        self.unparentButton.setObjectName("unparentButton")
        self.horizontalLayout_14.addWidget(self.unparentButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.step5Layout.addWidget(self.parGrp)
        self.verticalLayout.addLayout(self.step5Layout)
        self.step6Layout = QtWidgets.QVBoxLayout()
        self.step6Layout.setContentsMargins(-1, 4, -1, 4)
        self.step6Layout.setObjectName("step6Layout")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.step6 = QtWidgets.QLabel(self.centralwidget)
        self.step6.setObjectName("step6")
        self.horizontalLayout_18.addWidget(self.step6)
        self.resetBindPoseButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetBindPoseButton.setObjectName("resetBindPoseButton")
        self.horizontalLayout_18.addWidget(self.resetBindPoseButton)
        self.fixOrientsButton = QtWidgets.QPushButton(self.centralwidget)
        self.fixOrientsButton.setObjectName("fixOrientsButton")
        self.horizontalLayout_18.addWidget(self.fixOrientsButton)
        self.step6Layout.addLayout(self.horizontalLayout_18)
        self.surfEditGrp = QtWidgets.QGroupBox(self.centralwidget)
        self.surfEditGrp.setObjectName("surfEditGrp")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.surfEditGrp)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.editLockCheck = QtWidgets.QCheckBox(self.surfEditGrp)
        self.editLockCheck.setChecked(True)
        self.editLockCheck.setObjectName("editLockCheck")
        self.horizontalLayout_17.addWidget(self.editLockCheck)
        self.editMirCheck = QtWidgets.QCheckBox(self.surfEditGrp)
        self.editMirCheck.setChecked(True)
        self.editMirCheck.setObjectName("editMirCheck")
        self.horizontalLayout_17.addWidget(self.editMirCheck)
        self.editOrigCheck = QtWidgets.QCheckBox(self.surfEditGrp)
        self.editOrigCheck.setChecked(True)
        self.editOrigCheck.setObjectName("editOrigCheck")
        self.horizontalLayout_17.addWidget(self.editOrigCheck)
        self.surfaceEditButton = QtWidgets.QPushButton(self.surfEditGrp)
        self.surfaceEditButton.setObjectName("surfaceEditButton")
        self.horizontalLayout_17.addWidget(self.surfaceEditButton)
        self.step6Layout.addWidget(self.surfEditGrp)
        self.verticalLayout.addLayout(self.step6Layout)
        self.step7Layout = QtWidgets.QVBoxLayout()
        self.step7Layout.setContentsMargins(-1, 4, -1, 4)
        self.step7Layout.setObjectName("step7Layout")
        self.step7 = QtWidgets.QLabel(self.centralwidget)
        self.step7.setObjectName("step7")
        self.step7Layout.addWidget(self.step7)
        self.deformersGrp = QtWidgets.QGroupBox(self.centralwidget)
        self.deformersGrp.setObjectName("deformersGrp")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.deformersGrp)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.clusterHandleButton = QtWidgets.QPushButton(self.deformersGrp)
        self.clusterHandleButton.setObjectName("clusterHandleButton")
        self.horizontalLayout_7.addWidget(self.clusterHandleButton)
        self.setupBlendshapesButton = QtWidgets.QPushButton(self.deformersGrp)
        self.setupBlendshapesButton.setObjectName("setupBlendshapesButton")
        self.horizontalLayout_7.addWidget(self.setupBlendshapesButton)
        self.mergeBlendshapesButton = QtWidgets.QPushButton(self.deformersGrp)
        self.mergeBlendshapesButton.setObjectName("mergeBlendshapesButton")
        self.horizontalLayout_7.addWidget(self.mergeBlendshapesButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.step7Layout.addWidget(self.deformersGrp)
        self.verticalLayout.addLayout(self.step7Layout)
        SurfRigWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SurfRigWindow)
        self.symAxis.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SurfRigWindow)

    def retranslateUi(self, SurfRigWindow):
        SurfRigWindow.setWindowTitle(QtCompat.translate("SurfRigWindow", "Surface Rig Wizard", None, -1))
        self.step1.setText(QtCompat.translate("SurfRigWindow", "1: Rig settings", None, -1))
        self.symLabel.setToolTip(QtCompat.translate("SurfRigWindow", "Set the axis of symmetry for mirroring operations", None, -1))
        self.symLabel.setText(QtCompat.translate("SurfRigWindow", "World symmetry", None, -1))
        self.symAxis.setItemText(0, QtCompat.translate("SurfRigWindow", "None", None, -1))
        self.symAxis.setItemText(1, QtCompat.translate("SurfRigWindow", "X", None, -1))
        self.symAxis.setItemText(2, QtCompat.translate("SurfRigWindow", "Y", None, -1))
        self.symAxis.setItemText(3, QtCompat.translate("SurfRigWindow", "Z", None, -1))
        self.nameLabel.setToolTip(QtCompat.translate("SurfRigWindow", "Default name dictionary is:\n"
"{\n"
"\"convention\": \"{name}_{num:02}_{type}\",\n"
"\"surface\": \"SURF_RIG\",\n"
"\"rig group\": \"SURF_RIG_GRP\",\n"
"\"control\": \"CTRL\",\n"
"\"control group\": \"CTRL_GRP\",\n"
"\"offset group\": \"OFFSET_GRP\",\n"
"\"parent\": \"PAR\",\n"
"\"surface controls group\": \"SURF_CTRL_GRP\",\n"
"\"joint\": \"RIG_JNT\",\n"
"\"joint group\": \"JNTS_GRP\"\n"
"}\n"
"\n"
"Load a different file to change values for any/all keys.", None, -1))
        self.nameLabel.setText(QtCompat.translate("SurfRigWindow", "Naming conventions", None, -1))
        self.nameButton.setToolTip(QtCompat.translate("SurfRigWindow", "Default name dictionary is:\n"
"{\n"
"\"convention\": \"{name}_{num:02}_{type}\",\n"
"\"surface\": \"SURF_RIG\",\n"
"\"rig group\": \"SURF_RIG_GRP\",\n"
"\"control\": \"CTRL\",\n"
"\"control group\": \"CTRL_GRP\",\n"
"\"offset group\": \"OFFSET_GRP\",\n"
"\"parent\": \"PAR\",\n"
"\"surface controls group\": \"SURF_CTRL_GRP\",\n"
"\"joint\": \"RIG_JNT\",\n"
"\"joint group\": \"JNTS_GRP\"\n"
"}\n"
"\n"
"Load a different file to change values for any/all keys.", None, -1))
        self.nameButton.setText(QtCompat.translate("SurfRigWindow", "Load JSON", None, -1))
        self.step2.setText(QtCompat.translate("SurfRigWindow", "2: Select guide edges on mesh", None, -1))
        self.surfNameLabel.setText(QtCompat.translate("SurfRigWindow", "New surface Name:", None, -1))
        self.surfNameEdit.setPlaceholderText(QtCompat.translate("SurfRigWindow", "e.g., face_L_eyelids", None, -1))
        self.newSurfButton.setToolTip(QtCompat.translate("SurfRigWindow", "Create a NURBS surface using the selected continuous edges as a guide.", None, -1))
        self.newSurfButton.setText(QtCompat.translate("SurfRigWindow", "Create surface from guides", None, -1))
        self.simpleSurfButton.setToolTip(QtCompat.translate("SurfRigWindow", "Create a 2x3 span nurbs plane at the average position of selected edges.", None, -1))
        self.simpleSurfButton.setText(QtCompat.translate("SurfRigWindow", "Create simple surface", None, -1))
        self.initSurfButton.setToolTip(QtCompat.translate("SurfRigWindow", "Create hierarchy and attributes on selected user-made surface(s),\n"
"allowing them to be used fully with this surface rigging tool.", None, -1))
        self.initSurfButton.setText(QtCompat.translate("SurfRigWindow", "Initialize existing surface", None, -1))
        self.step3.setText(QtCompat.translate("SurfRigWindow", "3: Edit surface", None, -1))
        self.selectCVsButton.setText(QtCompat.translate("SurfRigWindow", "Mask CVs", None, -1))
        self.toggleJntsButton.setText(QtCompat.translate("SurfRigWindow", "Toggle Joints", None, -1))
        self.toggleSurfsButton.setText(QtCompat.translate("SurfRigWindow", "Toggle Surfaces", None, -1))
        self.step4.setText(QtCompat.translate("SurfRigWindow", "4: Add & position rig joints", None, -1))
        self.jntNameLabel.setText(QtCompat.translate("SurfRigWindow", "Joint Name:", None, -1))
        self.jntNameEdit.setPlaceholderText(QtCompat.translate("SurfRigWindow", "e.g., face_L_upperEyelid", None, -1))
        self.newJntButton.setToolTip(QtCompat.translate("SurfRigWindow", "Add a joint to the selected surface. The joint\'s \'allowed area\' may be\n"
"further limited via the rangeU and rangeV attributes on the joint itself.\n"
"When rigged, the joint will slide over its allowed area on the surface.", None, -1))
        self.newJntButton.setText(QtCompat.translate("SurfRigWindow", "Add new joint to surface", None, -1))
        self.step5.setText(QtCompat.translate("SurfRigWindow", "5: Create joint rig", None, -1))
        self.mirrorGrp.setTitle(QtCompat.translate("SurfRigWindow", "Mirror", None, -1))
        self.mirrorBoth.setToolTip(QtCompat.translate("SurfRigWindow", "Mirror the surface and all of its joints along the axis of symmetry.\n"
"\n"
"Also use this option if the surface has already been mirrored.\n"
"New joints and shape tweaks will be pushed onto the existing mirrored surface.", None, -1))
        self.mirrorBoth.setText(QtCompat.translate("SurfRigWindow", "Surface and joints", None, -1))
        self.mirrorJnts.setToolTip(QtCompat.translate("SurfRigWindow", "Mirror the surface\'s joints *onto the same surface* along the axis of symmetry.\n"
"\n"
"This option is for \"center\" surfaces with internal symmetry.", None, -1))
        self.mirrorJnts.setText(QtCompat.translate("SurfRigWindow", "Joints onto same surface", None, -1))
        self.searchLabel.setText(QtCompat.translate("SurfRigWindow", "Search:", None, -1))
        self.replaceLabel.setText(QtCompat.translate("SurfRigWindow", "Replace with:", None, -1))
        self.rigButton.setToolTip(QtCompat.translate("SurfRigWindow", "Create controls for each unrigged joint on the surfaces.\n"
"\n"
"If there are no unrigged joints, it will still perform any necessary mirroring options.\n"
"Useful for re-establishing symmetry after editing any surface with a mirror image.", None, -1))
        self.rigButton.setText(QtCompat.translate("SurfRigWindow", "Rig selected surfaces", None, -1))
        self.rigAllButton.setToolTip(QtCompat.translate("SurfRigWindow", "Create controls for each unrigged joint on the surfaces.\n"
"\n"
"If there are no unrigged joints, it will still perform any necessary mirroring options.\n"
"Useful for re-establishing symmetry after editing any surface with a mirror image.", None, -1))
        self.rigAllButton.setText(QtCompat.translate("SurfRigWindow", "Rig all surfaces", None, -1))
        self.sizeLabel.setToolTip(QtCompat.translate("SurfRigWindow", "Set the gross size for the selected surfaces\' control shapes. Attribute exists on each surface.", None, -1))
        self.sizeLabel.setText(QtCompat.translate("SurfRigWindow", "Control size", None, -1))
        self.distanceLabel.setToolTip(QtCompat.translate("SurfRigWindow", "Set the distance of controls from the selected surfaces. Attribute exists on each surface.", None, -1))
        self.distanceLabel.setText(QtCompat.translate("SurfRigWindow", "Control distance", None, -1))
        self.parGrp.setToolTip(QtCompat.translate("SurfRigWindow", "Create parent controls to affect multiple joint controls in a weighted and additive way.", None, -1))
        self.parGrp.setTitle(QtCompat.translate("SurfRigWindow", "Parent controls", None, -1))
        self.newParButton.setToolTip(QtCompat.translate("SurfRigWindow", "Create a new parent object for the selected controls.\n"
"The parent\'s orientation is based off of the surface of the LAST selected controls.", None, -1))
        self.newParButton.setText(QtCompat.translate("SurfRigWindow", "Create parent for selected", None, -1))
        self.parExistingButton.setToolTip(QtCompat.translate("SurfRigWindow", "Parent the first n selected controls to the last selected object", None, -1))
        self.parExistingButton.setText(QtCompat.translate("SurfRigWindow", "Parent selected to other", None, -1))
        self.mirParButton.setToolTip(QtCompat.translate("SurfRigWindow", "Mirror the selected parent controls.\n"
"\n"
"If a parent has already been mirrored, child weight attributes will be updated instead.", None, -1))
        self.mirParButton.setText(QtCompat.translate("SurfRigWindow", "Mirror selected parents", None, -1))
        self.unparentButton.setToolTip(QtCompat.translate("SurfRigWindow", "Remove all parents from the selected control.", None, -1))
        self.unparentButton.setText(QtCompat.translate("SurfRigWindow", "Unparent selected", None, -1))
        self.step6.setToolTip(QtCompat.translate("SurfRigWindow", "Use the Safe Surface Edit Tool to tweak a rigged and skinned surface\n"
"without having to worry about joint movement or bind pose.\n"
"\n"
"If you want to edit a surface beyond moving CVs (such as a rebuild),\n"
"use the provided Python context manager \"surfEditContext\" to do so\n"
"in a way that preserves joint position and skin cluster. E.G.,\n"
"with surfRig.surfEditContext():\n"
"    pmc.rebuildSurface()", None, -1))
        self.step6.setText(QtCompat.translate("SurfRigWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">6: Bind joints to mesh (recommended)</span></p></body></html>", None, -1))
        self.resetBindPoseButton.setToolTip(QtCompat.translate("SurfRigWindow", "Force a bind pose reset on the selected mesh.", None, -1))
        self.resetBindPoseButton.setText(QtCompat.translate("SurfRigWindow", "Reset bind pose", None, -1))
        self.fixOrientsButton.setToolTip(QtCompat.translate("SurfRigWindow", "Sometimes, controls on the same surface may have differing orientations,\n"
"particularly if the surface normal is nearly aligned with one of its local axes.\n"
"\n"
"Use this to unify control orientations for selected surfaces.", None, -1))
        self.fixOrientsButton.setText(QtCompat.translate("SurfRigWindow", "Fix control orients", None, -1))
        self.surfEditGrp.setToolTip(QtCompat.translate("SurfRigWindow", "Use the Safe Surface Edit Tool to tweak a rigged and skinned surface\n"
"without having to worry about joint movement or bind pose.\n"
"\n"
"If you want to edit a surface beyond moving CVs (such as a rebuild),\n"
"use the provided Python context manager \"surfEditContext\" to do so\n"
"in a way that preserves joint position and skin cluster. E.G.,\n"
"with surfRig.surfEditContext():\n"
"    pmc.rebuildSurface()", None, -1))
        self.surfEditGrp.setTitle(QtCompat.translate("SurfRigWindow", "Safe Surface Edit Tool", None, -1))
        self.editLockCheck.setToolTip(QtCompat.translate("SurfRigWindow", "ON: Preserve the joints\' original world-space position. Be aware that joints\n"
"are still \"stuck\" to the surface so accuracy depends on what tweaks are made.\n"
"OFF: Preserve joints\' UV surface-relative position.\n"
"\n"
"Skin cluster and bind pose are safely re-defined for resulting joint xforms.", None, -1))
        self.editLockCheck.setText(QtCompat.translate("SurfRigWindow", "Lock joints", None, -1))
        self.editMirCheck.setToolTip(QtCompat.translate("SurfRigWindow", "ON: Mirror any surface & joint changes to the surfaces\' mirror images (if applicable).\n"
"OFF: Do not mirror changes. Allows for asymmetric tweaks to be made.", None, -1))
        self.editMirCheck.setText(QtCompat.translate("SurfRigWindow", "Mirror edits", None, -1))
        self.editOrigCheck.setToolTip(QtCompat.translate("SurfRigWindow", "ON: If surfaces have deformers applied, hide the deformed shapes\n"
"and allow editing of the original, pre-deformer shapes instead.\n"
"OFF: Edit the post-deformer shapes.", None, -1))
        self.editOrigCheck.setText(QtCompat.translate("SurfRigWindow", "Original Shapes", None, -1))
        self.surfaceEditButton.setToolTip(QtCompat.translate("SurfRigWindow", "Enter Safe Surface Edit Tool.", None, -1))
        self.surfaceEditButton.setText(QtCompat.translate("SurfRigWindow", "Edit skinned surfaces", None, -1))
        self.step7.setText(QtCompat.translate("SurfRigWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">7: Deform surfaces as desired</span></p></body></html>", None, -1))
        self.deformersGrp.setToolTip(QtCompat.translate("SurfRigWindow", "The strength of mesh-guided surface rigging is its ability to define blendshape-ready regions.\n"
"SoftMod deformers, SoftClusters (available online), and MayaMuscle systems are also highly recommended.", None, -1))
        self.deformersGrp.setTitle(QtCompat.translate("SurfRigWindow", "Deformer tools", None, -1))
        self.clusterHandleButton.setToolTip(QtCompat.translate("SurfRigWindow", "Create control shapes for selected relative-mode deformer handles.\n"
"The controls move as their associated surfaces are deformed by other means.", None, -1))
        self.clusterHandleButton.setText(QtCompat.translate("SurfRigWindow", "Control selected deformer", None, -1))
        self.setupBlendshapesButton.setToolTip(QtCompat.translate("SurfRigWindow", "Add/update a shape under each control which drives the selected surfaces\' blendshape weights.\n"
"This allows easy and synchronizd animation of the same deformer from multiple controls.", None, -1))
        self.setupBlendshapesButton.setText(QtCompat.translate("SurfRigWindow", "Add blends to controls", None, -1))
        self.mergeBlendshapesButton.setToolTip(QtCompat.translate("SurfRigWindow", "Unify the blendshape driver shapes of all selected surfaces.\n"
"\n"
"Any driving attributes with the same name will be merged,\n"
"allowing multiple surface blendshapes to be driven via one channel.", None, -1))
        self.mergeBlendshapesButton.setText(QtCompat.translate("SurfRigWindow", "Merge blend controls", None, -1))

