# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Brendan/SkyDrive/maya/scripts/bkTools/rigGuiBase/rigGuiBaseQt.ui'
#
# Created: Sat Dec 23 23:22:47 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from bkTools.Qt import QtCompat, QtCore, QtGui, QtWidgets

class Ui_RigGuiBaseQt(object):
    def setupUi(self, RigGuiBaseQt):
        RigGuiBaseQt.setObjectName("RigGuiBaseQt")
        RigGuiBaseQt.resize(350, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(RigGuiBaseQt)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.refereceHeader = QtWidgets.QWidget(RigGuiBaseQt)
        self.refereceHeader.setMinimumSize(QtCore.QSize(300, 67))
        self.refereceHeader.setMaximumSize(QtCore.QSize(16777215, 67))
        self.refereceHeader.setObjectName("refereceHeader")
        self.headerLayout = QtWidgets.QVBoxLayout(self.refereceHeader)
        self.headerLayout.setContentsMargins(4, 2, 2, 2)
        self.headerLayout.setObjectName("headerLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.refLabel = QtWidgets.QLabel(self.refereceHeader)
        self.refLabel.setObjectName("refLabel")
        self.horizontalLayout_5.addWidget(self.refLabel)
        self.refPicker = QtWidgets.QComboBox(self.refereceHeader)
        self.refPicker.setObjectName("refPicker")
        self.horizontalLayout_5.addWidget(self.refPicker)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.headerLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newRefBut = QtWidgets.QPushButton(self.refereceHeader)
        self.newRefBut.setObjectName("newRefBut")
        self.horizontalLayout.addWidget(self.newRefBut)
        self.delRefBut = QtWidgets.QPushButton(self.refereceHeader)
        self.delRefBut.setObjectName("delRefBut")
        self.horizontalLayout.addWidget(self.delRefBut)
        self.headerLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.refereceHeader)
        self.selectionLayout = QtWidgets.QVBoxLayout()
        self.selectionLayout.setObjectName("selectionLayout")
        self.verticalLayout.addLayout(self.selectionLayout)
        self.toolsLayout = QtWidgets.QWidget(RigGuiBaseQt)
        self.toolsLayout.setMinimumSize(QtCore.QSize(300, 130))
        self.toolsLayout.setMaximumSize(QtCore.QSize(16777215, 130))
        self.toolsLayout.setAutoFillBackground(False)
        self.toolsLayout.setStyleSheet("")
        self.toolsLayout.setObjectName("toolsLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.toolsLayout)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setContentsMargins(5, 3, 5, 7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolsRadioLayout = QtWidgets.QHBoxLayout()
        self.toolsRadioLayout.setContentsMargins(21, -1, -1, -1)
        self.toolsRadioLayout.setObjectName("toolsRadioLayout")
        self.toolLabel = QtWidgets.QLabel(self.toolsLayout)
        self.toolLabel.setObjectName("toolLabel")
        self.toolsRadioLayout.addWidget(self.toolLabel)
        self.toolCheckBody = QtWidgets.QRadioButton(self.toolsLayout)
        self.toolCheckBody.setChecked(True)
        self.toolCheckBody.setObjectName("toolCheckBody")
        self.toolsRadioLayout.addWidget(self.toolCheckBody)
        self.toolCheckFace = QtWidgets.QRadioButton(self.toolsLayout)
        self.toolCheckFace.setObjectName("toolCheckFace")
        self.toolsRadioLayout.addWidget(self.toolCheckFace)
        self.toolCheckBoth = QtWidgets.QRadioButton(self.toolsLayout)
        self.toolCheckBoth.setObjectName("toolCheckBoth")
        self.toolsRadioLayout.addWidget(self.toolCheckBoth)
        self.toolsRadioLayout.setStretch(0, 1)
        self.toolsRadioLayout.setStretch(1, 1)
        self.toolsRadioLayout.setStretch(2, 1)
        self.toolsRadioLayout.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.toolsRadioLayout)
        self.selectionToolsLayout = QtWidgets.QHBoxLayout()
        self.selectionToolsLayout.setSpacing(5)
        self.selectionToolsLayout.setObjectName("selectionToolsLayout")
        self.resetSelection = QtWidgets.QPushButton(self.toolsLayout)
        self.resetSelection.setObjectName("resetSelection")
        self.selectionToolsLayout.addWidget(self.resetSelection)
        self.selectAll = QtWidgets.QPushButton(self.toolsLayout)
        self.selectAll.setObjectName("selectAll")
        self.selectionToolsLayout.addWidget(self.selectAll)
        self.selectUnkeyed = QtWidgets.QPushButton(self.toolsLayout)
        self.selectUnkeyed.setObjectName("selectUnkeyed")
        self.selectionToolsLayout.addWidget(self.selectUnkeyed)
        self.invertSelection = QtWidgets.QPushButton(self.toolsLayout)
        self.invertSelection.setObjectName("invertSelection")
        self.selectionToolsLayout.addWidget(self.invertSelection)
        self.verticalLayout_4.addLayout(self.selectionToolsLayout)
        self.reflectPoseGrp = QtWidgets.QGroupBox(self.toolsLayout)
        self.reflectPoseGrp.setAlignment(QtCore.Qt.AlignCenter)
        self.reflectPoseGrp.setObjectName("reflectPoseGrp")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.reflectPoseGrp)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.flipPose = QtWidgets.QPushButton(self.reflectPoseGrp)
        self.flipPose.setObjectName("flipPose")
        self.horizontalLayout_2.addWidget(self.flipPose)
        self.mirrorPoseLtR = QtWidgets.QPushButton(self.reflectPoseGrp)
        self.mirrorPoseLtR.setObjectName("mirrorPoseLtR")
        self.horizontalLayout_2.addWidget(self.mirrorPoseLtR)
        self.mirrorPoseRtL = QtWidgets.QPushButton(self.reflectPoseGrp)
        self.mirrorPoseRtL.setObjectName("mirrorPoseRtL")
        self.horizontalLayout_2.addWidget(self.mirrorPoseRtL)
        self.verticalLayout_4.addWidget(self.reflectPoseGrp)
        self.verticalLayout.addWidget(self.toolsLayout)

        self.retranslateUi(RigGuiBaseQt)
        QtCore.QMetaObject.connectSlotsByName(RigGuiBaseQt)

    def retranslateUi(self, RigGuiBaseQt):
        RigGuiBaseQt.setWindowTitle(QtCompat.translate("RigGuiBaseQt", "Generic Rig Gui", None, -1))
        self.refLabel.setText(QtCompat.translate("RigGuiBaseQt", "Active Rig Namespace:", None, -1))
        self.newRefBut.setText(QtCompat.translate("RigGuiBaseQt", "Add Namespace from Selection", None, -1))
        self.delRefBut.setText(QtCompat.translate("RigGuiBaseQt", "Remove Namespace", None, -1))
        self.toolLabel.setText(QtCompat.translate("RigGuiBaseQt", "Tools:", None, -1))
        self.toolCheckBody.setText(QtCompat.translate("RigGuiBaseQt", "Body Only", None, -1))
        self.toolCheckFace.setText(QtCompat.translate("RigGuiBaseQt", "Face Only", None, -1))
        self.toolCheckBoth.setText(QtCompat.translate("RigGuiBaseQt", "Both", None, -1))
        self.resetSelection.setText(QtCompat.translate("RigGuiBaseQt", "Reset Selected", None, -1))
        self.selectAll.setText(QtCompat.translate("RigGuiBaseQt", "Select All", None, -1))
        self.selectUnkeyed.setText(QtCompat.translate("RigGuiBaseQt", "Select Unkeyed", None, -1))
        self.invertSelection.setText(QtCompat.translate("RigGuiBaseQt", "Invert Selection", None, -1))
        self.reflectPoseGrp.setTitle(QtCompat.translate("RigGuiBaseQt", "Reflect Pose for Selected Controls", None, -1))
        self.flipPose.setText(QtCompat.translate("RigGuiBaseQt", "Flip Pose", None, -1))
        self.mirrorPoseLtR.setText(QtCompat.translate("RigGuiBaseQt", "Mirror L -->> R", None, -1))
        self.mirrorPoseRtL.setText(QtCompat.translate("RigGuiBaseQt", "Mirror R -->> L", None, -1))

